### ISSUE TITLE
Define Rough Game Direction

### ISSUE THREAD

**Issue by AlexSabourinDev** [AlexSabourinDev/IceBox#1]
Define what types of games we want to be creating with this engine.

Deliverables:
* Example games to use as inspiration guidelines for the project.
* Major game decisions that will define tech are ironed out. (Open world? 3D? Procedural?)

**Comment by AlexSabourinDev** [comment]
A potential game inspiration suggested was Okami
![okami-hd-switch-screenshot01](https://user-images.githubusercontent.com/27436276/93800003-f1d0f880-fc0d-11ea-944f-f0f858fbe0eb.jpg)

**Comment by mysteriosum** [comment]
[Cat Creative Direction_smallFile.pdf](https://github.com/AlexSabourinDev/IceBox/files/5307304/Cat.Creative.Direction_smallFile.pdf)
Here is the PDF of the inital creative direction pitch :)

**Comment by mysteriosum** [comment]
https://web.microsoftstream.com/video/c930aced-12e6-49b0-8d4c-91a8897683a1

^ a link to the pitch presentation (Wednesday, September 30, 2020)

**Comment by AlexSabourinDev** [comment]
I will mark this issue as closed, this seems appropriate for a first steps.
