### ISSUE TITLE
Create a C# Coding Standard

### ISSUE THREAD

**Issue by AlexSabourinDev** [AlexSabourinDev/IceBox#10]
**Is your feature request related to a problem? Please describe.**
The project is currently lacking a C# coding standard for the tools side of the engine. Create a coding standard Markdown document similar to the current one that exists for the C++ coding standard.

**Describe the solution you'd like**
Edit: Consider if we can use a tool for code formatting?

**Describe the acceptance criteria**
* A clear and concise coding standard markdown document is added to the primary repository.

**Additional context**
Consider matching the C++ coding standard document (Or changing that document to match the C# standard document) for project uniformity.

**Comment by skaarjslayer** [comment]
@AlexSabourinDev what do you envision when you talk about coding standard automation? I feel like you could do basic syntax checks but even then that'd probably take a bit to implement. Idk if a tool exists for it but even if it did my immediate concern would be the tool's flexibility. I'd rather retain full control over the exact standard than be bound to what a tool does/doesn't support. Another thing to consider is that, IMO, a standard goes beyond syntax and also covers preferential code design (for example, syntax of properties aside, should you prefer properties over getter/setters? what should properties be allowed to do? etc.) Code standard should answer these questions + we should keep in mind that a tool couldn't handle these for us.

Personal preference is to base C# standard off of existing Microsoft .NET standard with room for variation based on our needs. Though there'll need to be a serialization standard for data shared between engine/tools for sure.

**Comment by AlexSabourinDev** [comment]
On the C++ we have clang-format that runs to assure that the code meets basic formatting rules. It's mostly things like: brackets placement, pointer placement, etc. I have a Github action that runs and assures that code meets formatting constraints. It provides some presence of mind at least for some portions of the standard.

In terms of remaining standard, I agree that a tool can't do that. I should have worded the issue better. I've edited the issue to be a bit clearer

**Comment by AlexSabourinDev** [comment]
Closing as we've moved away from using C# in the project.
