### ISSUE TITLE
Define Overall Engine Architecture

### ISSUE THREAD

**Issue by AlexSabourinDev** [AlexSabourinDev/IceBox#2]
Define what type of direction the project's architecture will be taking?

Deliverables:
* Define main programming language.
* Define tools UI suite. (WPF? Qt?)
* Define Visual Studio project organization. (Many projects? Static libraries? Dynamic libraries?)
* Define systems organization. (How will systems interact? How will they be structured in the project?)

If discussions become too large for one particular topic we can split it into a new issue.

**Comment by AlexSabourinDev** [comment]
### Engine Language
For engine-side code, I would expect to use C++.

### For tools UI suite
For UI tools, maybe we want to use WPF?
If so, I'd like to de-risk how easy it is to interop with C#. I don't expect it to be incredibly difficult, but it will introduce some challenges.

### For Visual Studio Integration
I suggest we have this split of Visual Studio projects for now:
* Engine
* Tools
* Game/Samples

I think we can expect everything to be statically linked unless dynamic linkage is absolutely required. I also suggest we create new projects reactively if something requires it. More projects is more cognitive overhead, I'd like to keep it as simple as possible.

### For Systems interaction
I'd suggest splitting things based on their functionality level.
* Service Systems
* Engine Systems
* Game Systems

### Service Systems
Service systems code would have a minimal C-like API with as much hidden away into cpp files as possible. This makes modification much easier. (See how IBPlatform.h is written.) They should depend on very little from the engine and should be written in a somewhat isolated fashion.

The systems I expect to see in this layer are:
* Graphics Abstraction
* Physics
* Jobs
* Platforms
* Networking
* Etc

I'd expect to be able to write minimal sample projects in this area without needing to pull in a variety of dependencies.

### Engine Systems
These systems can depend on the service systems as well as other engine services. I think dependencies here are more acceptable. Some systems I'd expect to see here:
* UI
* Graphics front-end (mesh + material pairings)
* Physics front-end
* Network front-end
* Scripting (If this is something we think is valuable)

This could be the level at which the ECS core lives if we decide we want to go down that route.

### Game Systems
This is where game specific subsystems live such as:
* Game AI
* Gameplay logic
* Game scripts

**Comment by AlexSabourinDev** [comment]
After writing the WPF sample. It seems projects are likely better suited to be dynamically linked. If they aren't we won't be able to interop with C#.

**Comment by Razor162** [comment]
What are your reasons for WPF over Qt? I think Qt offers far less code duplication with easier to use design tools. There's the additional bonus of not having to travel down the road of a PInvoke/CLI debate. This is Thomas btw

**Comment by AlexSabourinDev** [comment]
Hah, I wouldn't have known 😆 

Because of familiarity across the group currently in the project. More people are familiar with WPF than they are with Qt, as a result, I figured dealing with the potential shotcomings of WPF would be worth it.

**Comment by Razor162** [comment]
Ahh that's fair

**Comment by AlexSabourinDev** [comment]
![IceBoxInfrastructure](https://user-images.githubusercontent.com/27436276/94950295-6af30a00-04b0-11eb-8a26-072e02112474.png)

**Comment by AlexSabourinDev** [comment]
https://web.microsoftstream.com/video/0a4e8d23-4a3a-4c2e-bd06-1f389f6ba05a

**Comment by AlexSabourinDev** [comment]
After a discussion with the group, here is a rough guideline on the direction of the engine.

## Layers
The engine will be split into roughly 3 conceptual layers. These layers represent the flow of dependencies.

In order from least dependent to most dependent we have:
* The core layer
* The service layer
* The frontend layer

The service layer depends on the core layer and the frontend layer depends on both the service and core layers.

Some example of modules in each layer are:
**Core Layer**
* Allocator
* Job System
* Platform
* Logging
* IO
* Math

**Service Layer**
* Rendering
* Physics
* Serialization
* Audio

**Frontend Layer**
* Rendering frontend
* Transform hierarchy
* Physics frontend
* Asset loader

The layers are not perfect abstractions, interdependence between layer modules is unavoidable but should be reduced. (Logging is likely to appear in many modules at every layer)

### Core Layer
The core layer represents core modules in use by the other engine layers. Things that are foundational such as job systems, allocators, platform abstraction, collections, etc. It should be easy to simply use a third party library as a core module if we wanted to.

### Service Layer
The service layer represent different services that are likely to be present in the engine such as rendering, physics, serialization, audio, etc. This layer represents different areas of functionality you might expect to see in an engine but is not directly interfacing with the engine's frontend. You should be able to use third party libraries like PhysX, BGFX and other libraries in this layer.

### Frontend Layer
The frontend layer is the layer that interacts most with game code, the editor and tools. The frontend communicates primarily with "assets". Assets are descriptions of data that can be fed to frontend systems to drive their functionality.

Some examples of assets are meshes, materials, components, transforms, etc.

The frontend layer is likely to interact with various parts of the service layer or individually. Ideally, if functionality gets large enough, separating a module into a frontend and service layer is likely a reasonable expectation to reduce the number of dependencies the core functionality would have on frontend portions of the engine.

Here is an example of how I expect the frontend to function:
- A cell is an asset that represents a collection of entities
- An entity is an asset that represents a collection of components
- A component describes data to be fed to the appropriate systems
- For example, a renderable component would describe a mesh and material pair
- The mesh and materials are assets that get fed to the rendering frontend.

On game startup
- The game requests a cell to be loaded
- The cell queues up loads of the entity assets
- The entity assets queue up loads of their components
- The components queue up loads of their data
- The data can then queue up a load of various other assets

Once an assets dependent loads are complete, a system is notified that an asset has been loaded. This implies that we have an event driven system to loading assets.

Taking the example of a renderable component, once it's mesh and material are loaded, the rendering frontend is notified that the renderable has been loaded. When the mesh and material had loaded, the rendering frontend was also notified to allow it to store the asset.

Once a renderable is loaded it's entity could be marked as loaded telling our entity system about our new entity. And finally, once our cell is loaded, it can prepare our entities for rendering.

## Asset storage
Assets will be primarily stored in JSON and compiled to a binary format by an offline content processing tool. Assets should be able to be both loaded from JSON and binary to avoid having to run the content processor for every game run.

The content processor would take our assets and package them up into a binary package alongside a header describing the contents of the package.

## Module style
I expect modules to be mainly a .h/.cpp pair. Reducing the number of files helps reduce compile times and conceptual overhead. We should split modules into multiple files reactively instead of proactively. Module APIs should be as minimal as possible, keeping our implementations within our cpp files.

## Rough Systems List
* Math
* Physics
* Rendering
* Jobs
* Allocator
* Serialization (JSON)
* Asset Loader
* Content Processor
* Rendering Frontend
* Physics Frontend
* Transform Hierarchy
* Audio
* Tools
* Profiler
* Memory Profiling
* Testing
* Scripting (Lua)
* Input
