### ISSUE TITLE
Tools design

### ISSUE THREAD

**Issue by mysteriosum** [AlexSabourinDev/IceBox#26]
High-level concepts for the basic game creation tools.

Acceptance Criteria
- Mockups
- Rationale
- Paradigm

**Comment by mysteriosum** [comment]
Systems to describe:
- IPB: Inspector, Properties, Behaviours
- Widget: for moving stuff around the scene
- Spaces: "rooms" hold every object in the game (including abstract ones and prefabs). Can be game spaces or abstract spaces.

**Comment by AlexSabourinDev** [comment]
Closing for now as part of a revamp of our github issues. Larger scale tasks like this will be tracked in Trello
