### ISSUE TITLE
Basic Renderer Framework

### ISSUE THREAD

**Issue by mysteriosum** [AlexSabourinDev/IceBox#27]
Renderer for the game engine!

ACCEPTANCE CRITERIA
Rendering API. To show its functionality, draw the following:
-Unit grid stretching off to infinity (dark blue)
-Cube rotating on the centre of the screen (neon green)

**Comment by mysteriosum** [comment]
For the background: #182229, for grid: #576773

**Comment by AlexSabourinDev** [comment]
The plan is to implement a clustered forward renderer in Vulkan. For now, I simply want to be able to define a single light in the shader and rotate the cube.

I will be pulling the code from my personal renderer and adapting it since writting Vulkan from scratch is quite tedious.

**Comment by AlexSabourinDev** [comment]
https://github.com/AlexSabourinDev/IceBox/tree/BaseRenderer
