### ISSUE TITLE
Basic Event System

### ISSUE THREAD

**Issue by mysteriosum** [AlexSabourinDev/IceBox#28]
The event system needs to read inputs and fire events across the project.

For this milestone, we expect:
-Read mouse position
-Read mouse clicks
-Fire events when these things occur

**Comment by AlexSabourinDev** [comment]
Managing events is definitely something we want to figure out for the engine. We'll have to consider if we want to attribute different input events to different windows - might be worthwhile to have a "consume" style API for events. TBD

This input event handling system should also consider in-game use.

**Comment by AlexSabourinDev** [comment]
Closing for now as part of a revamp of our github issues. Larger scale tasks like this will be tracked in Trello
