### ISSUE TITLE
Game Object framework

### ISSUE THREAD

**Issue by mysteriosum** [AlexSabourinDev/IceBox#29]
The "Thing" to be moved in this milestone is a Game Object. This is the Godfather of all Things in the game. The proto-thing, if you will.

For this deliverable, we expect:
-The cube from last milestone can be highlighted and un-highlighted via clicking events
-Print a log message with the cube's name

**Comment by AlexSabourinDev** [comment]
This will require a few things:
- Highlighting object support (maybe an extra highlight render pass?)
- Mouse to object detection which will require rough bounding boxes for collision detection. Or even simply a pixel perfect picker. TBD
- Defining the object approach for the game engine (properties and behaviours). Mysteriosum has some interesting ideas here, consider discussing it with them. I think it would be interesting to implement this in an effecient and flexible way.

When we get to this issue, please break it up into smaller issues for easier tracking and review.

**Comment by AlexSabourinDev** [comment]
Closing for now as part of a revamp of our github issues. Larger scale tasks like this will be tracked in Trello
