### ISSUE TITLE
Create Math Library

### ISSUE THREAD

**Issue by AlexSabourinDev** [AlexSabourinDev/IceBox#3]
Create a math library for IceBox.

Deliverables:
* Vec2, Vec3 and Vec4 class
* Mat3, Mat4 classes
* Useful utility functions

**Comment by martforg** [comment]
We should add quaternion to this list. We also need to determine some of the convention we want to use such as right/left handed coordinates, row/column major etc.

**Comment by AlexSabourinDev** [comment]
Implemented a basic math lib - will be adding to it on an as-needed basis
