### ISSUE TITLE
Investigate WPF Docking Strategy

### ISSUE THREAD

**Issue by AlexSabourinDev** [AlexSabourinDev/IceBox#7]

**Comment by JaredMacDonald** [comment]
There are 2 options that come to mind, Actipro and Sandock ( i think that is the name).  I've used both, I think Actipro was easier to use but it might require a license.  I can try to investigate more this weekend.

**Comment by AlexSabourinDev** [comment]
Thanks!

**Comment by JaredMacDonald** [comment]
Another option that I've used before that I forgot about earlier is AvalonDock.  Pretty sure they have a free option.

**Comment by AlexSabourinDev** [comment]
If we feel that docking isn't necessary, we can also simply omit it. But I'm assuming that it would be pretty essential to making a nice to use tool

**Comment by JaredMacDonald** [comment]
I think docking is pretty much an necessity at this point.  It's like copy and paste, for a good user experience it is pretty much expected.

**Comment by JaredMacDonald** [comment]
Here is a quick test of AvalonDock I threw together.  It will probably do the trick for what we need/want.
![image](https://user-images.githubusercontent.com/8752666/94998248-76146b80-057e-11eb-9e8e-8cb504ee9ea7.png)

**Comment by AlexSabourinDev** [comment]
Closed as of https://github.com/AlexSabourinDev/IceBox/commit/6e66492d133187c98ab4551f2fe9d38f3ff90ff9. Using AvalonDock from now on.
